#!/usr/bin/env bash
#
# Export an SVG (vector image) to a PNG (raster/'general' image).
#
# Requires inkscape.
#

usage() {
    cat <<EOF
Usage: ${0##*/} [-w width] [-h height] [-o outfile] file

Exports an SVG to a PNG using Inkscape.

Output defaults to [file].png (.svg extension removed).

  Options:
    -x width         specify export width
    -y height        specify export height
    -o outfile       specify outfile
    -h               display this help message
EOF
}

while getopts "x:y:o:h" opt; do
    case $opt in
        x) # specify width
            width="-w $OPTARG"
            ;;
        y) # specify height
            height="-h $OPTARG"
            ;;
        o) # specify outfile
            outfile="$OPTARG"
            ;;
        h) # display usage message
            usage
            exit 0
            ;;
    esac
done

# reset options (? for getopts)
shift $(($OPTIND-1))



if [ -z "$1" ]; then
    echo "error: file required"
    usage
    exit 1
fi

if [ -f "$1" ]; then
    image="$1"
else
    echo "error: not a file"
    usage
    exit 3
fi



if [ -z "$width" ]; then
    echo "${0##*/}: no width specified, not changing from default"
fi

if [ -z "$height" ]; then
    echo "${0##*/}: no height specified, not changing from default"
fi

if [ -z $outfile ]; then
    # ${filename%.*} removes the extension (i.e. characters past the last '.')
    outfile="${image%.*}.png"
fi



inkscape -e "$outfile" $width $height "$image"
